# criando Pipeline

name: Pipeline de produção
env:
  #variaveis de ambiente
  NODE_ENV: production
  # secrets é uma variavel de ambiente secreta do github
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

 #informações para rodar o codigo e acionar a Pipeline 
on:
  push:
    branches:
      - main

  #automação
jobs:

  
  job1:
    name: CI - Build e criação do artefato
    runs-on: ubuntu-latest
    steps:
      - name: Pegar código do Repositório
        uses: actions/checkout@v3

      - name: Instalando pacotes do npm
        run: npm install

      - name: Gerando documentação do swagger.json
        run: npm run autoDoc

      - name: Apagando pasta node_modules
        run: rm -rf node_modules

      - name: Apagando pasta .git
        run: rm -rf .git

      - name: Arquivos e pastas
        run: ls

      - name: Criando artefato ZIP do código buildado
        uses: actions/upload-artifact@v3
        with:
          name: artefato
          retention-days: 1
          path: ./



# CONFIGURANDO DEPLOY
  job2:
    name: CD - Deploy na Vercel
    #NEEDS É UMA DEPENDECIA QUE DEVER SER EXECUTADA
    needs: job1
    runs-on: ubuntu-latest
    #STEPS , SÃO SUBETAPAS 
    steps:
      - name: Baixando Artefato do código buildado
        uses: actions/download-artifact@v3
        with:
          name: artefato

      - name: Instalando pacotes do npm
        run: npm install

      - name: Arquivos e pastas do artefato
        run: ls

      - name: Instalando CLI da Vercel
        run: npm install --global vercel@latest

      - name: Buscando informações de ambiente no Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Buildando artefatos do projeto
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy de artefatos do projeto na Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}